### PR TITLE
General maintenance

### PR DESCRIPTION
**Pull request by nohli**
* Update deprecated theme variables
* Update gradle to fix Android build of example app
* Increase `compileSdkVersion` to fix Android build of example app
* auto-format

### CODE REVIEW

**Comment by AlexV525** [comment]
We should also raise the environment constraints, right?

**Comment by nohli** [comment]
I guess the new theme variables were first introduced in Flutter 2.10, updated the constrains.

**Review by AlexV525 — APPROVED** [review]
👍

**Comment by nohli** [comment]
@AlexV525 could you please allow access for the [workflow](https://github.com/fluttercandies/flutter_hsvcolor_picker/actions/runs/5985413804/job/16237603826) to publish to pub.dev?

FYI I've had the same issue with a new package that the link wouldn't work... But after I moved the package to a `verified publisher` on pub.dev, it worked without the need to any further authorization.

**Comment by AlexV525** [comment]
> FYI I've had the same issue with a new package that the link wouldn't work... But after I moved the package to a `verified publisher` on pub.dev, it worked without the need to any further authorization.

Do you mean the pub does not allow unknown publisher packages to update? Or we're having an infra issue? The credential is not owned by me so I'll have to collaborate with the team if necessary.

**Comment by AlexV525** [comment]
I see the outdated authorization logs. I'll update them or transfer the package to our publisher ASAP.

**Comment by nohli** [comment]
All I know is that the GitHub action asks you to open a link on pub.dev, which doesn't seem to be valid.
And when the package is under the umbrella of a verified publisher, it just works without any link.

I can also volunteer of adding it to my account, but I recollect there was an account from fluttercandies.

Thanks for your help 🙏🏽

**Comment by AlexV525** [comment]
@nohli I've updated the credential and the package has been transferred to fluttercandies.com publisher. Could you verify the publish again?

**Comment by nohli** [comment]
@AlexV525 thank you, great job!
I've jut restarted the workflow, and now it's published.

**Pull request merged**
